apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certs
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: applications/certs
    repoURL: https://github.com/dirien/vcluster-webinar.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true