apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-2
  labels:
    team: team-2
    department: development
    project: backend
    distro: k3s
    version: v1.23.2-k3s1
  annotations:
    argocd.argoproj.io/sync-wave: "99"
spec:
  destination:
    name: in-cluster
    namespace: team-2
  project: default
  source:
    repoURL: 'https://charts.loft.sh'
    targetRevision: 0.6.0-alpha.7
    helm:
      values: |-
        vcluster:
          image: rancher/k3s:v1.23.2-k3s1
          extraArgs:
            - --service-cidr=10.32.0.0/12
        ingress:
          enabled: false
    chart: vcluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true