apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-1
  labels:
    team: team-1
    department: development
    project: frontend
    distro: k3s
    version: v1.21.4-k3s1
  annotations:
    argocd.argoproj.io/sync-wave: "99"
spec:
  destination:
    name: in-cluster
    namespace: team-1
  project: default
  source:
    repoURL: 'https://charts.loft.sh'
    targetRevision: 0.6.0-alpha.7
    helm:
      values: |-
        rbac:
          clusterRole:
            create: true
          role:
            create: true
            extended: true
        syncer:
          extraArgs:
            - --tls-san=team-1.ediri.cloud
            - --out-kube-config-server=https://team-1.ediri.cloud
        vcluster:
          image: rancher/k3s:v1.21.4-k3s1
          extraArgs:
            - --service-cidr=10.32.0.0/12
        ingress:
          enabled: true
          host: team-1.ediri.cloud
          annotations:
            external-dns.alpha.kubernetes.io/hostname: team-1.ediri.cloud
            external-dns.alpha.kubernetes.io/ttl: "60"
    chart: vcluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true