apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ingress-nginx/ingress-nginx.yaml
  - external-dns/external-dns.yaml
  - cert-manager/cert-manager.yaml
  - kube_prometheus_stack/kube-prometheus-stack.yaml
  - certs/certs.yaml
  - argocd/argocd.yaml
  - vcluster/vcluster.yaml