apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "99"
spec:
  destination:
    name: in-cluster
    namespace: team-2
  project: default
  source:
    repoURL: 'https://charts.loft.sh'
    targetRevision: 0.6.0-alpha.7
    helm:
      values: |-
        vcluster:
          image: k0sproject/k0s:v1.23.1-k0s.1
          extraArgs:
            - --service-cidr=10.32.0.0/12
        ingress:
          enabled: true
          ingressClassName: nginx
          host: team-2.ediri.cloud
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
    chart: vcluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true