apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.0.15
    helm:
      values: |-
        serviceAccount:
          automountServiceAccountToken: true
        controller:
          extraArgs:
            enable-ssl-passthrough: ""
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          allowSnippetAnnotations: false
    chart: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
