name: Pulumi

on:
  push:
    tags:
      - '*'
  pull_request:
    paths:
      - "infrastructure/controlplane-scaleway/**"

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17
      - run:  |
          go mod download
          curl -fsSL https://get.pulumi.com | sh
          pulumi plugin install resource scaleway v0.1.8 --server https://dl.briggs.work/pulumi/releases/plugins
        working-directory: infrastructure/controlplane-scaleway
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: ./infrastructure/controlplane-scaleway
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  up:
    name: Up
    runs-on: ubuntu-latest
    needs:
      - preview
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17
      - run:  |
          go mod download
          curl -fsSL https://get.pulumi.com | sh
          pulumi plugin install resource scaleway v0.1.8 --server https://dl.briggs.work/pulumi/releases/plugins
        working-directory: infrastructure/controlplane-scaleway
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: ./infrastructure/controlplane-scaleway
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}